[build]
<<<<<<< HEAD
=======
  command = """
    curl -sSL https://github.com/rust-lang/mdBook/releases/latest/download/mdbook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz | tar -xzf -
    chmod +x mdbook
    mv mdbook /usr/local/bin/mdbook
    mdbook build docs
  """
>>>>>>> 4353be7f6d4c69fe28fed848074db5a7ecde35be
  publish = "docs/book"
  command = """
  curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.40/mdbook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz -o mdbook.tar.gz
  tar -xzf mdbook.tar.gz
  chmod +x mdbook
  mv mdbook /usr/local/bin/
  mdbook build docs
  """

[build.environment]
  RUST_LOG = "info"
