[build]
  command = """
  mkdir -p $HOME/bin
  curl -sSL https://github.com/rust-lang/mdBook/releases/latest/download/mdbook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz \
    | tar -xz -C $HOME/bin
  export PATH=$HOME/bin:$PATH
  mdbook build docs
  """
  publish = "docs/book"
