[build]
  command = """
    curl -sSL https://github.com/rust-lang/mdBook/releases/latest/download/mdbook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz | tar -xzf -
    chmod +x mdbook
    mv mdbook /usr/local/bin/mdbook
    mdbook build docs
  """
  publish = "docs/book"
