[build]
  command = """
  curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.40/mdbook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz -o mdbook.tar.gz
  tar -xzf mdbook.tar.gz
  chmod +x mdbook
  ./mdbook build docs
  """

[build.environment]
  RUST_LOG = "info"
